services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal

  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public
      - internal
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./session.session
        target: /app/session.session
      - type: bind
        source: ./mycreds.json
        target: /app/mycreds.json
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data:
