services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    networks:
      - internal
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public
      - internal
    depends_on:
      - postgres
      - redis
    volumes:
      - ./session.session:/app/session.session
      - ./authorized_user.json:/root/.config/gspread/authorized_user.json
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /app/app
        - action: sync
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  postgres_data:
  redis_data:
