[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = False
disable_error_code = import-not-found

[mypy-aiogram.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True

[mypy-gspread.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-dotenv.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-telethon.*]
ignore_missing_imports = True

[mypy-yoyo.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True
